"""
make_golden.py -- writes the reference ("golden") files the TypeScript tests
compare against. Run check_fidelity.py first: it proves harness.py reproduces
simgenv2.generate_one bit-for-bit, which is what makes these files trustworthy.

usage:  python reference/make_golden.py            (writes tests/golden/)

Each case file stores the sampled parameters plus the intermediate arrays of
the deterministic pipeline. Super-grid (384x384) arrays are stored as a
stride-4 sample (rows/cols 2, 6, ..., 382) to keep the repo small; detector
(96x96) arrays and the PSF kernel are stored in full.
"""

import base64
import copy
import json
import math
import os
import platform
import sys

import numpy as np

import harness as H

sg, sgt = H.sg, H.sgt
ROOT = os.path.dirname(H.HERE)
OUT = os.path.join(ROOT, "tests", "golden")

# Seeds chosen to cover the branches of generate_one (see coverage printout).
SEEDS = [1, 3, 7, 14, 15, 21, 23, 45]
S4 = slice(2, None, 4)   # stride-4 sample of the 384 super-grid
S8 = slice(4, None, 8)   # stride-8 sample used for ray-shooting checks


def b64(arr, dtype):
    a = np.ascontiguousarray(np.asarray(arr, dtype=dtype))
    return {"dtype": np.dtype(dtype).name, "shape": list(a.shape),
            "b64": base64.b64encode(a.astype(a.dtype.newbyteorder("<")).tobytes()).decode()}


def to_jsonable(x):
    if isinstance(x, dict):
        return {k: to_jsonable(v) for k, v in x.items()}
    if isinstance(x, (list, tuple)):
        return [to_jsonable(v) for v in x]
    if isinstance(x, (np.floating,)):
        return float(x)
    if isinstance(x, (np.integer,)):
        return int(x)
    return x


def case_record(name, p, st, extra=None):
    realized_fwhm_arcsec = st["psf_kernel_info"]["realized_fwhm_pix"] * sg.SUP_PIXEL_SCALE
    lens_light_det = sg.downsample(st["lens_counts_sup"], sg.OVERSAMPLE).astype(np.float32)
    # lens_flux truth needs norm_m = max(GT, noisy LENSED). The TS port draws its own
    # noise, so the golden file pins norm_m to the value from the numpy noise draw.
    rec = {
        "name": name,
        "params": to_jsonable(p),
        "scalars": {
            "theta_E_raw": p["theta_E_raw"],
            "src_mag_final": st["src_mag_final"], "lens_mag_final": st["lens_mag_final"],
            "src_total_counts": st["src_total_counts"], "lens_total_counts": st["lens_total_counts"],
            "ratio_history": st["ratio_history"], "tries": st["tries"],
            "psf_realized_fwhm_pix": st["psf_kernel_info"]["realized_fwhm_pix"],
            "psf_coma_applied": st["psf_kernel_info"]["coma_applied"],
            "ll_center_x": st["ll_center_x"], "ll_center_y": st["ll_center_y"],
            "realized_fwhm_arcsec": realized_fwhm_arcsec,
        },
        "arrays": {
            "xs_s8": b64(st["xs"][S8, S8], np.float64),
            "ys_s8": b64(st["ys"][S8, S8], np.float64),
            "src_pattern_s4": b64(st["src_pattern"][S4, S4], np.float32),
            "lensed_src_counts_sup_s4": b64(st["lensed_src_counts_sup"][S4, S4], np.float32),
            "lens_light_sup_pattern_s4": b64(st["lens_light_sup_pattern"][S4, S4], np.float32),
            "image_conv_sup_s4": b64(st["image_conv_sup"][S4, S4], np.float64),
            "psf_sup": b64(st["psf_sup"], np.float32),
            "GT": b64(st["GT"], np.float32),
            "LENSED_counts": b64(st["LENSED_counts"], np.float32),
            "lens_light_det": b64(lens_light_det, np.float32),
        },
    }
    if extra:
        rec.update(extra)
    return rec


def main():
    os.makedirs(OUT, exist_ok=True)
    manifest = {"cases": [], "versions": {
        "python": platform.python_version(), "numpy": np.__version__,
        "lenstronomy": __import__("lenstronomy").__version__,
        "astropy": __import__("astropy").__version__, "scipy": __import__("scipy").__version__,
    }, "note": "generated by reference/make_golden.py; do not edit by hand"}

    for seed in SEEDS:
        p, st, LENSED, noise_info, tr = H.simulate_seeded(seed)
        rec = case_record(f"seed{seed:03d}", p, st, {
            "seed": seed,
            "truth": {"values": to_jsonable(tr["truth"]), "maskbits": tr["maskbits"], "clean": tr["clean"],
                      "norm_m": tr["norm_m"], "ll_amp": tr["ll_amp"]},
        })
        fn = f"case_seed{seed:03d}.json"
        json.dump(rec, open(os.path.join(OUT, fn), "w"))
        cov = dict(nfw=p["nfw"] is not None, subhalos=len(p["subhalos"]),
                   extras=len(p["source"]["extras"]), clumps=p["source"]["clumps"] is not None,
                   spiral=p["source"]["spiral_phase"] is not None,
                   clip=p["theta_E_clip"], tries=st["tries"])
        manifest["cases"].append({"file": fn, "coverage": cov})
        print(fn, cov)

    # Forced case: make the lens 4 mag brighter than the source so the
    # peak-ratio loop in generate_one actually runs (it never fires for the
    # simgenv2 priors in practice -- see VERIFICATION.md).
    sg.set_seed(2)
    p = H.sample_params()
    p = copy.deepcopy(p)
    p["photometry"]["lens_mag"] = p["photometry"]["src_mag"] - 4.0
    st = H.render(p)
    rec = case_record("forced_ratio_loop", p, st)
    json.dump(rec, open(os.path.join(OUT, "case_forced_ratio_loop.json"), "w"))
    manifest["cases"].append({"file": "case_forced_ratio_loop.json",
                              "coverage": {"tries": st["tries"], "note": "lens_mag forced to src_mag-4"}})
    print("case_forced_ratio_loop.json tries =", st["tries"], st["ratio_history"])

    # --- small unit-level references -------------------------------------
    from astropy import units as u
    from astropy.cosmology import Planck15 as cosmo
    zs = [0.1, 0.25, 0.5, 0.7, 0.9, 1.2, 1.5, 2.0, 2.5, 3.0]
    cosmo_ref = {
        "D_A": [[z, float(cosmo.angular_diameter_distance(z).to(u.Mpc).value)] for z in zs],
        "D_C": [[z, float(cosmo.comoving_distance(z).to(u.Mpc).value)] for z in zs],
        "D_A12": [[z1, z2, float(cosmo.angular_diameter_distance_z1z2(z1, z2).to(u.Mpc).value)]
                  for z1, z2 in [(0.25, 0.9), (0.3, 1.5), (0.5, 2.0), (0.7, 3.0), (0.6, 0.9)]],
        "thetaE": [[s, zl, zsrc, float(sg.sigma_to_thetaE_arcsec(s, zl, zsrc))]
                   for s, zl, zsrc in [(160, 0.25, 0.9), (240, 0.5, 2.0), (320, 0.7, 3.0), (200, 0.3, 1.1)]],
        "Ogamma0": float(cosmo.Ogamma0), "Onu0": float(cosmo.Onu0), "Ode0": float(cosmo.Ode0),
    }

    psf_ref = []
    for (fwhm, ptype, ellip, angle, beta, coma_prob, coma_u) in [
        (0.06, "GAUSSIAN", 0.0, 0.0, 3.5, 0.0, 0.5),
        (0.10, "GAUSSIAN", 0.08, 2.1, 3.5, 0.0, 0.5),
        (0.08, "MOFFAT", 0.05, 0.7, 3.5, 0.0, 0.5),
        (0.12, "MOFFAT", 0.2, 4.0, 2.5, 0.0, 0.5),
        (0.09, "GAUSSIAN", 0.03, 1.0, 3.5, 1.0, 0.1),   # coma branch
    ]:
        k, info = sgt.make_psf_kernel_fixed(fwhm, sg.SUP_PIXEL_SCALE, psf_type=ptype, ellip=ellip,
                                            angle=angle, beta=beta, rng=H._FixedDraw(coma_u), coma_prob=coma_prob)
        psf_ref.append({"args": {"fwhm_arcsec": fwhm, "pixel_scale": sg.SUP_PIXEL_SCALE, "type": ptype,
                                 "ellip": ellip, "angle": angle, "beta": beta,
                                 "coma_prob": coma_prob, "coma_u": coma_u},
                        "info": to_jsonable(info), "kernel": b64(k, np.float32)})

    truth_ref = []
    configs = [
        (["SIE"], [{"theta_E": 1.2, "e1": 0.1, "e2": -0.05, "center_x": 0.01, "center_y": -0.02}]),
        (["SIE", "SHEAR", "NFW"], [{"theta_E": 1.0, "e1": -0.2, "e2": 0.1, "center_x": 0.0, "center_y": 0.0},
                                   {"gamma1": -0.03, "gamma2": -0.04},
                                   {"alpha_Rs": 0.5, "Rs": 12.0, "center_x": 0.0, "center_y": 0.0}]),
        (["SIE", "SHEAR", "NFW", "SIS"], [{"theta_E": 1.4, "e1": 0.0, "e2": 0.3, "center_x": 0.02, "center_y": 0.03},
                                          {"gamma1": 0.05, "gamma2": 0.0},
                                          {"alpha_Rs": 0.5, "Rs": 7.0, "center_x": 0.2, "center_y": -0.1},
                                          {"theta_E": 0.03, "center_x": 0.3, "center_y": 0.1}]),
    ]
    psf_infos = [
        {"realized_fwhm_pix": 2.1, "psf_type": "GAUSSIAN", "beta": 3.5, "ellip": 0.05, "angle": 5.5, "coma_applied": False},
        {"realized_fwhm_pix": 1.7, "psf_type": "MOFFAT", "beta": 3.1, "ellip": 0.02, "angle": 0.3, "coma_applied": False},
        {"realized_fwhm_pix": 0.45, "psf_type": "AIRY", "beta": 3.5, "ellip": 0.0, "angle": 0.0, "coma_applied": False},
    ]
    for (lml, kw), psfi in zip(configs, psf_infos):
        t, m, c = sgt.truth_from_lenstronomy(lml, kw, pixel_scale=sg.PIXEL_SCALE, image_size=sg.IMAGE_SIZE,
                                             psf_info=psfi, lens_light_info={"Re_arcsec": 0.5, "n_sersic": 4.0,
                                                                             "amp_at_Re_normalized": 0.02})
        truth_ref.append({"lens_model_list": lml, "kwargs_lens": kw, "psf_info": psfi,
                          "truth": to_jsonable(t), "maskbits": m, "clean": c})

    wrap_ref = [[a, sgt._wrap_axis_angle(a)] for a in
                [-7.0, -3.5, -2.0, -math.pi / 2, -1.0, 0.0, 0.5, math.pi / 2, 2.0, 3.5, 7.0]]

    units = {"cosmology": cosmo_ref, "psf": psf_ref, "truth": truth_ref, "wrap_axis_angle": wrap_ref}
    json.dump(units, open(os.path.join(OUT, "units.json"), "w"))
    manifest["units"] = "units.json"
    json.dump(manifest, open(os.path.join(OUT, "manifest.json"), "w"), indent=2)
    print("wrote", OUT)


if __name__ == "__main__":
    main()
